# You can validate this file at: https://lint.travis-ci.org

language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/data/
  - $HOME/data_resources/

#Use the default script command of travis with maven which is mvn test -B
#Before running script, for maven projects travis executes 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'

before_script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn javadoc:javadoc 
- mvn test -B 

