package com.ibm.drl.hbcp.predictor.nodes.normalization;

import static org.junit.Assert.assertEquals;

import com.ibm.drl.hbcp.core.attributes.normalization.normalizers.MixedGenderNormalizer;
import org.junit.Test;

public class MixedGenderNormalizerTest {

    @Test
    public void testGetNormalForm() {
        String[] inputTexts = {
                "% (N) Male 79.7 (966)",
                "% (No) of men 45",
                "% fem",
                "(62%) women",
                "(Female)(49%",
                "(female/male)22/65",
                "(n) Men 87",
                "- female 56.8%",
                "142",
                "196181",
                "3.9%",
                "47.5%",
                "54%",
                "330 (65.6)",
                "45%female55%male",
                "48% were female",
                "50% male50% female",
                "50%males",
                "51 male68 female",
                "5 (113 male,",
                "64%) were male and 53 (36%) female",
                "70.0% male",
                "Fem",
                "Fema59Mal40",
                "Female",
                "Female,60.5",
                "Female30.2",
                "Female35%",
                "Female46.0%",
                "Female49",
                "Female60.5Male39.5",
                "Female70.",
                "Female (%)49",
                "Female 60%",
                "Female 61.2%",
                "Female gender46",
                "Gender (% women)69.8",
                "Gender (ma5",
                "Mal4",
                "Male",
                "Male/female46/44",
                "Male21.3",
                "Male43.3%",
                "Male44.7±2.7",
                "Male45",
                "Male46.2Female53.8",
                "Male68Æ67",
                "Male69Female31",
                "Male81.7%Female15.1%Transgender3.2%",
                "Male 100",
                "Male 62.0",
                "Male 98.8Female 1.2",
                "Male sex94.1",
                "Males",
                "Males55",
                "MalesFemales",
                "Men75.80",
                "Men78%",
                "Men95",
                "Men 61",
                "Men 868 (100)",
                "Sex (female) 63.0%",
                "Women",
                "Women26.8Men73.2",
                "Women40%Men60%",
                "Women50.2",
                "Women (%)42",
                "Women comprised 40%",
                "f e m a l e 5 0 . 0",
                "f mal (98",
                "fe- male",
                "female",
                "female45.7",
                "female (90%)",
                "females.",
                "male",
                "male52.8",
                "male64 %",
                "male93%",
                "male 64%",
                "males",
                "men",
//                "men44-6%",
                "men46%",
                "men (n=89)women (n=110)",
                "women",
                "women(54%",
                "women60",
                "womenmen",
                };
        String[] outputTexts = {
                "M (79.7) F (20.3)",
                "M (45) F (55)",
                "M (unspecified) F (unspecified)",
                "M (38) F (62)",
                "M (51) F (49)",
                "M (74.71) F (25.29)",
                "M (unspecified) F (unspecified)",
                "M (43.2) F (56.8)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (55) F (45)",
                "M (52) F (48)",
                "M (50) F (50)",
                "M (50) F (50)",
                "M (42.86) F (57.14)",
                "M (unspecified) F (unspecified)",
                "M (64) F (36)",
                "M (70) F (30)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (39.5) F (60.5)",
                "M (69.8) F (30.2)",
                "M (65) F (35)",
                "M (54) F (46)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (51) F (49)",
                "M (40) F (60)",
                "M (38.8) F (61.2)",
                "M (unspecified) F (unspecified)",
                "M (30.2) F (69.8)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (51.11) F (48.89)",
                "M (21.3) F (78.7)",
                "M (43.3) F (56.7)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (46.2) F (53.8)",
                "M (unspecified) F (unspecified)",
                "M (69) F (31)",
                "M (81.7) F (15.1)",
                "M (unspecified) F (unspecified)",
                "M (62) F (38)",
                "M (98.8) F (1.2)",
                "M (94.1) F (5.9)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (75.8) F (24.2)",
                "M (78) F (22)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (37) F (63)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (60) F (40)",
                "M (49.8) F (50.2)",
                "M (58) F (42)",
                "M (60) F (40)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (54.3) F (45.7)",
                "M (10) F (90)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                "M (52.8) F (47.2)",
                "M (64) F (36)",
                "M (93) F (7)",
                "M (64) F (36)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
//                "M (6) F (94)",
                "M (46) F (54)",
                "M (44.72) F (55.28)",
                "M (unspecified) F (unspecified)",
                "M (46) F (54)",
                "M (unspecified) F (unspecified)",
                "M (unspecified) F (unspecified)",
                };
        for (int i = 0; i < inputTexts.length; i++) {
            assertEquals(outputTexts[i], MixedGenderNormalizer.getNormalForm(inputTexts[i]));
        }
        
    }

}
